# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kyaw_vsi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1215, 726)
        Dialog.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 100, 120);  /* more red, less pastel */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 80, 100);   /* slightly darker on hover */\n"
"    box-shadow: 0 0 12px rgba(255, 0, 0, 0.7);  /* red glow */\n"
"}")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(50, 70, 820, 560))
        self.graphicsView.setStyleSheet("QGraphicsView {\n"
"    border: 2px solid #444;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    background-color: #1e1e1e;  /* soft dark background */\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 660, 111, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(144, 238, 144);  /* light pastel green */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 220, 120);  /* slightly deeper on hover */\n"
"    outline: 4px solid rgba(0, 255, 0, 1);  /* maximum green glow */\n"
"    outline-offset: 0px;\n"
"    border: none;\n"
"    box-shadow: 0 0 16px rgba(0, 255, 0, 0.9); /* outer green glow effect */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 660, 111, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 170);  /* soft pastel yellow */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 245, 140);  /* slightly deeper yellow */\n"
"    outline: 4px solid rgba(255, 215, 0, 1);  /* strongest solid yellow */\n"
"    outline-offset: 0px;\n"
"    box-shadow: 0 0 16px rgba(255, 215, 0, 1);  /* intense yellow glow */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(900, 70, 273, 187))
        self.graphicsView_4.setStyleSheet("QGraphicsView {\n"
"    border: 2px solid #444;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    background-color: #1e1e1e;  /* soft dark background */\n"
"}")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(910, 280, 271, 61))
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    color: rgb(204, 153, 255);  /* pastel purple text */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Base indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(180, 100, 240);  /* darker purple border */\n"
"    box-shadow: 0 0 8px rgb(180, 100, 240);  /* darker purple glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(204, 153, 255);  /* pastel purple fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(150, 0, 220);  /* deeper purple glow */\n"
"}")
        self.checkBox_2.setIconSize(QtCore.QSize(22, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 660, 111, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(173, 216, 230);  /* light pastel blue */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(158, 204, 223);  /* slightly darker on hover */\n"
"    outline: 4px solid rgba(0, 140, 255, 1);  /* strong full blue outline */\n"
"    outline-offset: 0px;\n"
"    box-shadow: 0 0 16px rgba(0, 140, 255, 0.9); /* glowing effect */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(900, 10, 281, 51))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 371, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(750, 660, 111, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 100, 120);  /* main red button */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: 2px solid transparent;  /* neutral border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 80, 100);  /* darker on hover */\n"
"    border: 2px solid rgba(255, 0, 0, 0.6);  /* red glow border */\n"
"    outline: 2px solid rgba(255, 0, 0, 0.3); /* subtle outer glow */\n"
"    outline-offset: 0px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(910, 340, 261, 61))
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 179, 102);  /* pastel orange */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(255, 204, 153);  /* soft border */\n"
"    box-shadow: 0 0 8px rgb(255, 140, 0);  /* darker orange glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(255, 179, 102);  /* pastel fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(255, 128, 0);  /* bold orange glow */\n"
"}")
        self.checkBox_3.setIconSize(QtCore.QSize(22, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(910, 490, 281, 41))
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 105, 180, 150),\n"
"        stop:0.5 rgba(255, 182, 193, 220),\n"
"        stop:1 rgba(255, 105, 180, 150)\n"
"    );\n"
"    box-shadow: 0px 0px 12px rgba(255, 105, 180, 180); /* Note: Not all Qt versions support this */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    image: url(\"shuriken.png\");\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: -18px 0;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(910, 420, 191, 61))
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(1110, 430, 91, 41))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 2px solid rgb(90, 90, 90);\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 14px;\n"
"    selection-background-color: rgb(255, 192, 203);\n"
"    selection-color: black;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgb(255, 160, 200);\n"
"    box-shadow: 0 0 8px rgb(255, 160, 200);\n"
"}\n"
"\n"
"/* Glow on focus */\n"
"QTextEdit:focus {\n"
"    border: 2px solid rgb(255, 200, 220);\n"
"    box-shadow: 0 0 12px rgb(255, 200, 220);\n"
"}\n"
"\n"
"/* Hide scrollbars visually and functionally */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(900, 550, 321, 181))
        self.textEdit_2.setStyleSheet("")
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Start Cam"))
        self.pushButton_2.setText(_translate("Dialog", "Stop Cam"))
        self.checkBox_2.setText(_translate("Dialog", " Facial Recognition (On/Off)"))
        self.pushButton_3.setText(_translate("Dialog", "Snapshot"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">Live MediaPipe Landmarks</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">Kyaw VSI CW2 [Live WebCam]</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "Quit"))
        self.checkBox_3.setText(_translate("Dialog", "Gesture Detection (On/Off)"))
        self.label_5.setText(_translate("Dialog", "<html>\n"
"  <head/>\n"
"  <body>\n"
"    <p>\n"
"      <span style=\"font-size:18pt; font-weight:600; font-style:italic; color: white;\">\n"
"        Confidence Threshold:\n"
"      </span>\n"
"    </p>\n"
"  </body>\n"
"</html>"))
