# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kyaw_vsi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1215, 726)
        Dialog.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 100, 120);  /* more red, less pastel */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 80, 100);   /* slightly darker on hover */\n"
"    box-shadow: 0 0 12px rgba(255, 0, 0, 0.7);  /* red glow */\n"
"}")
        self.StartPB = QtWidgets.QPushButton(Dialog)
        self.StartPB.setGeometry(QtCore.QRect(50, 660, 111, 41))
        self.StartPB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(144, 238, 144);  /* light pastel green */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 220, 120);  /* slightly deeper on hover */\n"
"    outline: 4px solid rgba(0, 255, 0, 1);  /* maximum green glow */\n"
"    outline-offset: 0px;\n"
"    border: none;\n"
"    box-shadow: 0 0 16px rgba(0, 255, 0, 0.9); /* outer green glow effect */\n"
"}")
        self.StartPB.setObjectName("StartPB")
        self.StopPB = QtWidgets.QPushButton(Dialog)
        self.StopPB.setGeometry(QtCore.QRect(330, 660, 111, 41))
        self.StopPB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 170);  /* soft pastel yellow */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 245, 140);  /* slightly deeper yellow */\n"
"    outline: 4px solid rgba(255, 215, 0, 1);  /* strongest solid yellow */\n"
"    outline-offset: 0px;\n"
"    box-shadow: 0 0 16px rgba(255, 215, 0, 1);  /* intense yellow glow */\n"
"}")
        self.StopPB.setObjectName("StopPB")
        self.MPview = QtWidgets.QGraphicsView(Dialog)
        self.MPview.setGeometry(QtCore.QRect(900, 70, 301, 187))
        self.MPview.setStyleSheet("QGraphicsView {\n"
"    border: 2px solid #444;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    background-color: #1e1e1e;  /* soft dark background */\n"
"}")
        self.MPview.setObjectName("MPview")
        self.FR = QtWidgets.QCheckBox(Dialog)
        self.FR.setGeometry(QtCore.QRect(910, 280, 101, 61))
        self.FR.setStyleSheet("QCheckBox {\n"
"    color: rgb(204, 153, 255);  /* pastel purple text */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Base indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(180, 100, 240);  /* darker purple border */\n"
"    box-shadow: 0 0 8px rgb(180, 100, 240);  /* darker purple glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(204, 153, 255);  /* pastel purple fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(150, 0, 220);  /* deeper purple glow */\n"
"}")
        self.FR.setIconSize(QtCore.QSize(22, 16))
        self.FR.setObjectName("FR")
        self.SnapPB = QtWidgets.QPushButton(Dialog)
        self.SnapPB.setGeometry(QtCore.QRect(190, 660, 111, 41))
        self.SnapPB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(173, 216, 230);  /* light pastel blue */\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    outline: none;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(158, 204, 223);  /* slightly darker on hover */\n"
"    outline: 4px solid rgba(0, 140, 255, 1);  /* strong full blue outline */\n"
"    outline-offset: 0px;\n"
"    box-shadow: 0 0 16px rgba(0, 140, 255, 0.9); /* glowing effect */\n"
"}")
        self.SnapPB.setObjectName("SnapPB")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(900, 10, 281, 51))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 371, 31))
        self.label_3.setObjectName("label_3")
        self.QuitPB = QtWidgets.QPushButton(Dialog)
        self.QuitPB.setGeometry(QtCore.QRect(750, 660, 111, 41))
        self.QuitPB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 100, 120);  /* main red button */\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: 2px solid transparent;  /* neutral border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 80, 100);  /* darker on hover */\n"
"    border: 2px solid rgba(255, 0, 0, 0.6);  /* red glow border */\n"
"    outline: 2px solid rgba(255, 0, 0, 0.3); /* subtle outer glow */\n"
"    outline-offset: 0px;\n"
"}")
        self.QuitPB.setObjectName("QuitPB")
        self.GD = QtWidgets.QCheckBox(Dialog)
        self.GD.setGeometry(QtCore.QRect(910, 340, 101, 61))
        self.GD.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 179, 102);  /* pastel orange */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(255, 204, 153);  /* soft border */\n"
"    box-shadow: 0 0 8px rgb(255, 140, 0);  /* darker orange glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(255, 179, 102);  /* pastel fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(255, 128, 0);  /* bold orange glow */\n"
"}")
        self.GD.setIconSize(QtCore.QSize(22, 16))
        self.GD.setObjectName("GD")
        self.Slider = QtWidgets.QSlider(Dialog)
        self.Slider.setGeometry(QtCore.QRect(910, 490, 281, 41))
        self.Slider.setAutoFillBackground(False)
        self.Slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(0, 191, 255, 150),\n"
"        stop:0.5 rgba(135, 206, 250, 220),\n"
"        stop:1 rgba(0, 191, 255, 150)\n"
"    );\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    image: url(\"shuriken.png\");\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: -18px 0;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(910, 420, 191, 61))
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.THtextEdit = QtWidgets.QTextEdit(Dialog)
        self.THtextEdit.setGeometry(QtCore.QRect(1110, 430, 91, 41))
        self.THtextEdit.setStyleSheet("QTextEdit {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 2px solid rgb(90, 90, 90);\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 14px;\n"
"    selection-background-color: rgb(255, 192, 203);\n"
"    selection-color: black;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgb(255, 160, 200);\n"
"    box-shadow: 0 0 8px rgb(255, 160, 200);\n"
"}\n"
"\n"
"/* Glow on focus */\n"
"QTextEdit:focus {\n"
"    border: 2px solid rgb(255, 200, 220);\n"
"    box-shadow: 0 0 12px rgb(255, 200, 220);\n"
"}\n"
"\n"
"/* Hide scrollbars visually and functionally */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.THtextEdit.setObjectName("THtextEdit")
        self.Manual = QtWidgets.QTextEdit(Dialog)
        self.Manual.setGeometry(QtCore.QRect(900, 550, 321, 181))
        self.Manual.setStyleSheet("")
        self.Manual.setObjectName("Manual")
        self.MainView = QtWidgets.QLabel(Dialog)
        self.MainView.setGeometry(QtCore.QRect(60, 80, 791, 501))
        self.MainView.setAutoFillBackground(False)
        self.MainView.setText("")
        self.MainView.setScaledContents(True)
        self.MainView.setObjectName("MainView")
        self.BR = QtWidgets.QCheckBox(Dialog)
        self.BR.setGeometry(QtCore.QRect(1040, 340, 161, 61))
        self.BR.setStyleSheet("QCheckBox {\n"
"    color: rgb(255, 0, 144);  /* magenta text */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Base indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(255, 0, 144);  /* magenta border */\n"
"    box-shadow: 0 0 8px rgb(255, 0, 144);  /* magenta glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(255, 0, 144);  /* magenta fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(200, 0, 120);  /* deeper magenta glow */\n"
"}")
        self.BR.setIconSize(QtCore.QSize(22, 16))
        self.BR.setObjectName("BR")
        self.Vol = QtWidgets.QCheckBox(Dialog)
        self.Vol.setGeometry(QtCore.QRect(1040, 280, 101, 61))
        self.Vol.setStyleSheet("QCheckBox {\n"
"    color: rgb(102, 255, 255);  /* pastel cyan */\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"/* Indicator box */\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    transition: all 0.3s;\n"
"}\n"
"\n"
"/* Glow on hover */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(153, 255, 255);  /* soft cyan border */\n"
"    box-shadow: 0 0 8px rgb(0, 200, 255);  /* vibrant cyan glow */\n"
"}\n"
"\n"
"/* Glow when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(102, 255, 255);  /* pastel cyan fill */\n"
"    border: 2px solid white;\n"
"    box-shadow: 0 0 10px rgb(0, 180, 255);  /* deeper cyan glow */\n"
"}")
        self.Vol.setIconSize(QtCore.QSize(22, 16))
        self.Vol.setObjectName("Vol")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.StartPB.setText(_translate("Dialog", "Start Cam"))
        self.StopPB.setText(_translate("Dialog", "Stop Cam"))
        self.FR.setText(_translate("Dialog", " Facial"))
        self.SnapPB.setText(_translate("Dialog", "Snapshot"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">Live MediaPipe Landmarks</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">Kyaw VSI CW2 [Live WebCam]</span></p></body></html>"))
        self.QuitPB.setText(_translate("Dialog", "Quit"))
        self.GD.setText(_translate("Dialog", "Gesture"))
        self.label_5.setText(_translate("Dialog", "<html>\n"
"  <head/>\n"
"  <body>\n"
"    <p>\n"
"      <span style=\"font-size:18pt; font-weight:600; font-style:italic; color: white;\">\n"
"        Confidence Threshold:\n"
"      </span>\n"
"    </p>\n"
"  </body>\n"
"</html>"))
        self.BR.setText(_translate("Dialog", "Brightness"))
        self.Vol.setText(_translate("Dialog", "Volume"))
